[package]
name = "iron-hmac"
version = "0.3.0"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "HMAC middleware for the Iron HTTP framework"
license = "MIT"
readme = "README.md"
repository = "https://github.com/jwilm/iron-hmac"
documentation = "https://jwilm.github.io/iron-hmac/latest/iron_hmac/"

[features]
default = ["hmac-rust-crypto"]

# Use openssl HMAC/SHA256 implementations
hmac-openssl = ["openssl"]

# Use rust-crypto HMAC/SHA256 implementations
hmac-rust-crypto = ["rust-crypto"]

[dependencies]
bodyparser = "0"
constant_time_eq = "0.1.0"
iron = "0.2"
openssl = { version = "0.7", optional = true }
persistent = "0"
rust-crypto = { version = "0.2", optional = true }
rustc-serialize = "0.3"
url = "0.5"

[dev-dependencies.hyper]
version = "0.7"
default-features = false
