[package]
name = "iron-hmac"
version = "0.1.0"
authors = ["Joe Wilm <joe@jwilm.com>"]

[dependencies]
openssl = "0.7"
iron = "0.2"
url = "0.5"
bodyparser = "0.0"
persistent = "*"
hyper = "0.7"
rustc-serialize = "0.3"
