[package]
name = "iron-hmac"
version = "0.1.1"
authors = ["Joe Wilm <joe@jwilm.com>"]
description = "HMAC middleware for the Iron HTTP framework"
license = "MIT"
readme = "README.md"
repository = "https://github.com/jwilm/iron-hmac"
documentation = "https://jwilm.github.io/iron-hmac/latest/iron_hmac/"

[dependencies]
rust-crypto = "0.2.34"
url = "0.5"
bodyparser = "0.0"
persistent = "0.0"
rustc-serialize = "0.3"
constant_time_eq = "0.1.0"

[dependencies.iron]
version = "0.2"
default-features = false

[dev-dependencies.hyper]
version = "0.7"
default-features = false
